# Markdown renderer configuration
[goldmark.renderer]
unsafe = false

[tableOfContents]
endLevel = 6
ordered = false
startLevel = 2

[highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
